# Site settings
title: Jun Zeng's Homepage
email: zengjunsjtu@berkeley.edu
description: "Robotics Science"
baseurl: ""
url: "http://junzengx14.github.io"
blogurl: "http://junzengx14.github.io"
github_username:  junzengx14

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
